version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.3.1

parameters:
  samplevar:
    type: string
    default: ""

jobs:
  generate-var:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - continuation:
          configuration_path: ./continuation-config.yml
          parameters: parameters.json

workflows:
  workflow1:
    jobs:
      - build
 
