version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.3.1
  path-filtering: circleci/path-filtering@0.0.2

jobs:
  generate-var:
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision : main
          output-path: parameters.json
          mapping : |
            INCA/.* INCA true
      - run:
          name: Get value for build-version parameter and update parameters.json
          command: |
            Build_Version=$(cat OryxVersion.txt)
            JSON_PARAMS=$(cat parameters.json)
            echo $JSON_PARAMS | jq --arg version $Build_Version '. += {"build-version": $version}' > parameters.json
      - continuation/continue:
          configuration_path: ./.circleci/continuation-config.yml
          parameters: parameters.json

workflows:
  generate-var:
    jobs: 
      - generate-var
 
