version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.3.1

parameters:
  build-version:
    type: string
    default: ""

jobs:
  generate-var:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Get value for build-version parameter
          command: |
            Build_Version=$(cat OryxVersion.txt)
            cat OryxVersion.txt
            echo $Build_Version
            jq -n --arg version $Build_Version '.build-version = $version' > parameters.json
      - run: cat parameters.json
      - continuation/continue:
          configuration_path: ./continuation-config.yml
          parameters: parameters.json

workflows:
  workflow1:
    jobs:
      - generate-var
 
