version: 2.1

orbs:
  win: circleci/windows@2.2.0

parameters:
  build-version:
    type: string
    default: ""
  INCA:
    type: boolean
    default: false

jobs:
  job-1:
    executor:
      name: win/default
      size: "medium"
    environment:
      BUILD_VERSION: << pipeline.parameters.build-version >>
      INCA: << pipeline.parameters.INCA >>
    steps:
      - checkout
      - run:
          name: Check value of sample variable
          shell: bash.exe
          command: |
            echo $BUILD_VERSION 
            echo $INCA
      - run:
          name: Install jFrog CLI
          shell: powershell.exe
          command: choco install jfrog-cli
      - run:
          name: Install jFrog CLI
          shell: powershell.exe
          command: jfrog.exe config add
      - run:
          name: Jfrog Config
          shell: powershell.exe
          command: jfrog c s
      - run:
          name: Jq Install
          shell: powershell.exe
          command: choco install jq --true 
      - run:
          name: Jfrog_build_Version
          shell: powershell.exe
          command: |
           # code for building jfrog, can use $BUILD_VERSION

workflows:
  Parameter_Build:
    jobs:
      - job-1
